# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Get Some Tacos

GET {{address}}/tacos


### Get the Catalog

GET {{address}}/catalog


### Add New Software

POST {{address}}/new-software
Authorization: {{bossToken}}
Content-Type: application/json

{
    "title": "Baldur's Gate",
    "description": "Game"
}

### Get a New Software Item

GET {{address}}/new-software/b0025560-22da-410b-aaae-fb4ffd1418f9
Authorization: {{sueToken}}


### Get a list of new software

GET {{address}}/new-software
Authorization: {{sueToken}}


### Delete One

DELETE {{address}}/new-software/023724ff-67d8-41c6-9a82-150d93ed7b6a
Authorization: {{bossToken}}
