# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Get Some Tacos

GET {{address}}/tacos


### Get the Catalog

GET {{address}}/catalog


### Add New Software

POST {{address}}/new-software
Authorization: {{bossToken}}
Content-Type: application/json

{
    "title": "Jetbrains Rider",
    "description": ".NET IDE"
}

### Get a New Software Item

GET {{address}}/new-software/b0025560-22da-410b-aaae-fb4ffd1418f9
Authorization: {{sueToken}}