@address = http://localhost:1337


POST {{address}}/techs
Content-Type: application/json

{
  "firstName": "Jules",
  "lastName": "Jones",
  "email": "jules@compuserve.com",
  "phone": "867-5309"
}


### 

GET {{address}}/techs/d9512c21-0e4c-4ea8-993f-b2f91d10de1d
